USE ChimuraTest;

CREATE TABLE GuildRPG(
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    GuildID BIGINT UNSIGNED NOT NULL,
    
    PRIMARY KEY(ID),
    FOREIGN KEY(GuildID) REFERENCES Guild(ID)
) ENGINE=INNODB;

ALTER TABLE RPGCharacter
    ADD MemberID INT UNSIGNED NOT NULL
        AFTER ID,
    ADD GuildRPGID INT UNSIGNED NOT NULL
        AFTER MemberID,
    ADD FOREIGN KEY(GuildRPGID) REFERENCES GuildRPG(ID)
;

ALTER TABLE Equipment
    ADD GuildRPGID INT UNSIGNED NOT NULL
        AFTER ID,
    ADD FOREIGN KEY(GuildRPGID) REFERENCES GuildRPG(ID)
;

ALTER TABLE Spell
    ADD GuildRPGID INT UNSIGNED NOT NULL
        AFTER ID,
    ADD FOREIGN KEY(GuildRPGID) REFERENCES GuildRPG(ID)
;

ALTER TABLE Class
    ADD GuildRPGID INT UNSIGNED NOT NULL
        AFTER ID,
    ADD FOREIGN KEY(GuildRPGID) REFERENCES GuildRPG(ID)
;

ALTER TABLE Stat
    ADD GuildRPGID INT UNSIGNED NOT NULL
        AFTER ID,
    ADD FOREIGN KEY(GuildRPGID) REFERENCES GuildRPG(ID)
;

ALTER TABLE Belief
    ADD GuildRPGID INT UNSIGNED NOT NULL
        AFTER ID,
    ADD FOREIGN KEY(GuildRPGID) REFERENCES GuildRPG(ID)
;

ALTER TABLE Divinity
    ADD GuildRPGID INT UNSIGNED NOT NULL
        AFTER ID,
    ADD FOREIGN KEY(GuildRPGID) REFERENCES GuildRPG(ID)
;

ALTER TABLE Specie
    ADD GuildRPGID INT UNSIGNED NOT NULL
        AFTER ID,
    ADD FOREIGN KEY(GuildRPGID) REFERENCES GuildRPG(ID)
;

ALTER TABLE Genre
    ADD GuildRPGID INT UNSIGNED NOT NULL
        AFTER ID,
    ADD FOREIGN KEY(GuildRPGID) REFERENCES GuildRPG(ID)
;

ALTER TABLE StatAlteration
    ADD GuildRPGID INT UNSIGNED NOT NULL
        AFTER ID,
    ADD FOREIGN KEY(GuildRPGID) REFERENCES GuildRPG(ID)
;