USE ChimuraTest;

CREATE TABLE Member(
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Muted BIT NOT NULL,
    UserID BIGINT UNSIGNED NOT NULL,
    GuildID BIGINT UNSIGNED NOT NULL,
    
    PRIMARY KEY(ID),
    FOREIGN KEY(UserID) REFERENCES User(ID),
    FOREIGN KEY(GuildID) REFERENCES Guild(ID)
) ENGINE=INNODB;

CREATE TABLE AutoRole(
    ID BIGINT UNSIGNED NOT NULL,
    GuildID BIGINT UNSIGNED NOT NULL,
    
    PRIMARY KEY(ID),
    FOREIGN KEY(GuildID) REFERENCES Guild(ID)
) ENGINE=INNODB;

CREATE TABLE ReactionRole(
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    MessageID BIGINT UNSIGNED NOT NULL,
    RoleID BIGINT UNSIGNED NOT NULL,
    GuildID BIGINT UNSIGNED NOT NULL,
    Emote VARCHAR(20),
    Emoji VARCHAR(20),
    
    PRIMARY KEY(ID),
    FOREIGN KEY(GuildID) REFERENCES Guild(ID)
) ENGINE=INNODB;