---
--- Generated by EmmyLua(https://github.com/EmmyLua)
---
--- A class representing a Class object
--- Its attributes are :
--- - ID            : INT NOT NULL UNSIGNED (PRIMARY KEY) (DatabaseGenerated)
--- - GuildRPGID    : INT NOT NULL UNSIGNED
--- - Name          : VARCHAR NULLABLE
--- - Description   : VARCHAR NULLABLE
---
--- @class Class
--- @author RedNeath
--- @since 1.0.0
---
--- @licence MIT (https://github.com/Kamigami-no-Tanjou/KoishiTetsu-x-RyouwasaChimura/blob/main/LICENSE)
---
Class = {
    id = nil, -- : int
    guildRPGId = nil, -- : int
    name = nil, -- : string
    description = nil, -- : string
    guildRPG = nil, -- : GuildRPG
    statAlterations = nil -- : StatAlteration[]
}

---
--- The Class' constructor (will be used to rebuild Class object instances out of a table retrieved from a json string)
---
--- @param object table The table to create an object from (leave nil if not used).
--- @param id number The ID of the line of Class it represents.
--- @param guildRPGId number The ID of the GuildRPG this Class belongs to.
--- @param name string The name of the class.
--- @param description string The description of the class.
--- @param guildRPG GuildRPG The GuildRPG object it is attached to.
--- @param statAlterations StatAlteration[] The array of StatAlterations that are inducted by the class.
---
--- @return Class the new instance of Class.
---
function Class:new(object,
                   id,
                   guildRPGId,
                   name,
                   description,
                   guildRPG,
                   statAlterations
)
    --For safety (if the table is nil)
    object = object or {}

    --We provide 'object' Class's metamethods & properties
    setmetatable(object, self)
    self.__index = self

    --And we finally give it its default values
    --[[
    Important here to affect values to 'object' and not 'self' !! Because editing 'self' would mean modifying the
    prototype, hence modifying all its sub-classes/objects!
    --]]
    object.id = tonumber(id or object.id) or nil
    object.guildRPGId = tonumber(guildRPGId or object.guildRPGId) or nil
    object.name = name or object.name or nil
    object.description = description or object.description or nil

    --These values are not meant to be inserted in the database (or perhaps not the standard way)
    object.guildRPG = guildRPG or object.guildRPG or nil
    object.statAlterations = statAlterations or object.statAlterations or nil

    return object
end