---
--- Generated by EmmyLua(https://github.com/EmmyLua)
---
--- A class representing a GuildRPG object
--- Its attributes are :
--- - ID                : INT NOT NULL UNSIGNED (PRIMARY KEY) (DatabaseGenerated)
--- - GuildID           : BIGINT NOT NULL UNSIGNED (=Discord ID)
---
--- @class GuildRPG
--- @author RedNeath
--- @since 1.0.0
---
--- @licence MIT (https://github.com/Kamigami-no-Tanjou/KoishiTetsu-x-RyouwasaChimura/blob/main/LICENSE)
---
GuildRPG = {
    id = 0,
    guildId = 0,
    guild = {},
    characters = {},
    equipments = {},
    spells = {},
    classes = {},
    stats = {},
    beliefs = {},
    divinities = {},
    species = {},
    genres = {},
    statAlterations = {}
}

---
--- The GuildRPG's constructor (will be used to rebuild GuildRPG object instances out of a table retrieved from a json
--- string)
---
--- @param object table The table to create an object from (leave nil if not used).
--- @param id number The ID of the line of GuildRPG it represents.
--- @param guildId number The ID of the Guild this GuildRPG belongs to.
--- @param guild Guild The Guild object it is attached to.
--- @param characters Character[] The array of characters included in the RPG.
--- @param equipments Equipment[] The array of equipments included in the RPG.
--- @param spells Spell[] The array of spells available in the RPG.
--- @param classes Class[] The array of classes available in the RPG.
--- @param stats Stat[] The array of stats that characters will have in the RPG.
--- @param beliefs Belief[] The array of religions every character may believe in within the RPG.
--- @param divinities Divinity[] The array of divinities existing within the RPG.
--- @param species Specie[] The array of Specie the players can chose from to create their character(s).
--- @param genres Genre[] The array of genres the characters may be.
--- @param statAlterations StatAlteration[] The array of stat alterations for every specificity of the classes & species.
---
--- @return GuildRPG the new instance of GuildRPG.
---
function GuildRPG:new(object,
                      id,
                      guildId,
                      guild,
                      characters,
                      equipments,
                      spells,
                      classes,
                      stats,
                      beliefs,
                      divinities,
                      species,
                      genres,
                      statAlterations
)
    --For safety (if the table is nil)
    object = object or {}

    --We provide 'object' GuildRPG's metamethods & properties
    setmetatable(object, self)
    self.__index = self

    --And we finally give it its default values
    --[[
    Important here to affect values to 'object' and not 'self' !! Because editing 'self' would mean modifying the
    prototype, hence modifying all its sub-classes/objects!
    --]]
    object.id = tonumber(id or object.id) or nil
    object.guildId = tonumber(guildId or object.guildId) or nil

    --These values are not meant to be inserted in the database (or perhaps not the standard way)
    object.guild = guild or object.guild or nil
    object.characters = characters or object.characters or nil
    object.equipments = equipments or object.equipments or nil
    object.spells = spells or object.spells or nil
    object.classes = classes or object.classes or nil
    object.stats = stats or object.stats or nil
    object.beliefs = beliefs or object.beliefs or nil
    object.divinities = divinities or object.divinities or nil
    object.species = species or object.species or nil
    object.genres = genres or object.genres or nil
    object.statAlterations = statAlterations or object.statAlterations or nil

    return object
end