---
--- Generated by EmmyLua(https://github.com/EmmyLua)
---
--- A class representing a Spell object
--- Its attributes are :
--- - ID            : INT NOT NULL UNSIGNED (PRIMARY KEY) (DatabaseGenerated)
--- - GuildRPGID    : INT NOT NULL UNSIGNED
--- - Name          : VARCHAR NULLABLE
--- - Description   : VARCHAR NULLABLE
--- - DailyQuota    : INT NULLABLE
---
--- @class Spell
--- @author RedNeath
--- @since 1.0.0
---
--- @licence MIT (https://github.com/Kamigami-no-Tanjou/KoishiTetsu-x-RyouwasaChimura/blob/main/LICENSE)
---
Spell = {
    id = 0,
    guildRPGId = 0,
    name = "",
    description = "",
    dailyQuota = 0,
    guildRPG = {}
}

---
--- The Spell's constructor (will be used to rebuild Spell object instances out of a table retrieved from a json string)
---
--- @param object table The table to create an object from (leave nil if not used).
--- @param id number The ID of the line of Spell it represents.
--- @param guildRPGId number The ID of the GuildRPG this Spell belongs to.
--- @param name string The name of the spell.
--- @param description string The description on the spell.
--- @param dailyQuota number The amount of time the spell can be used per day.
--- @param guildRPG GuildRPG The GuildRPG object it is attached to.
---
--- @return Spell the new instance of Spell.
---
function Spell:new(object,
                  id,
                  guildRPGId,
                  name,
                  description,
                  dailyQuota,
                  guildRPG
)
    --For safety (if the table is nil)
    object = object or {}

    --We provide 'object' Spell's metamethods & properties
    setmetatable(object, self)
    self.__index = self

    --And we finally give it its default values
    --[[
    Important here to affect values to 'object' and not 'self' !! Because editing 'self' would mean modifying the
    prototype, hence modifying all its sub-classes/objects!
    --]]
    object.id = tonumber(id or object.id) or nil
    object.guildRPGId = tonumber(guildRPGId or object.guildRPGId) or nil
    object.name = name or object.name or nil
    object.description = description or object.description or nil
    object.dailyQuota = dailyQuota or object.dailyQuota or nil

    --These values are not meant to be inserted in the database (or perhaps not the standard way)
    object.guildRPG = guildRPG or object.guildRPG or nil

    return object
end