---
--- Generated by EmmyLua(https://github.com/EmmyLua)
---
--- A script that contains all global functions that may be useful to entities.
---
--- @author RedNeath
--- @since 1.0.0
---
--- @licence MIT (https://github.com/Kamigami-no-Tanjou/KoishiTetsu-x-RyouwasaChimura/blob/main/LICENSE)
--- @return self
---
local EntityUtils = {}

---
--- Returns the boolean value of the given parameter.
--- ```
--- 1.
--- String  : => Attempt to convert it to a number.
---           -> success    => Number
---           -> fail       => Other
---
--- 2.
--- Boolean :
---           -> true       => true
---           -> false      => false
--- Number  :
---           -> 0          => false
---           -> ]0;+inf[   => true
---           -> ]-inf;0[   => error (illegal argument)
--- Other   : => nil
--- ```
---
--- @param val any Whether a boolean or a number.
---
--- @return boolean The boolean value corresponding to the given parameter, according to the table discussed earlier.
---
function EntityUtils.affectBool(val)
    local typeVal = type(val)
    local realVal

    -- If it is a string, we try to get a number out of it
    if typeVal == "string" then
        realVal = tonumber(val)
        typeVal = type(realVal)
    else
        realVal = val
    end

    if typeVal == "boolean" then
        -- Nothing to do, the value is already a boolean
        return realVal
    elseif typeVal == "number" then
        assert(realVal >= 0, "{ \"err\":\"Illegal argument!\" }")

        return (realVal > 0)
    else
        return nil
    end
end

return EntityUtils