---
--- Generated by EmmyLua(https://github.com/EmmyLua)
---
--- A script that contains all global functions that may be useful to entities.
---
--- @author RedNeath
--- @since 1.0.0
---
--- @licence MIT (https://github.com/Kamigami-no-Tanjou/KoishiTetsu-x-RyouwasaChimura/blob/main/LICENSE)
---

---
--- Returns the boolean value of the given parameter.
--- Boolean : -> true       => true
---           -> false      => false
--- Number  : -> 0          => false
---           -> ]0;+inf[   => true
---           -> ]-inf;0[   => error (illegal argument)
--- Other => nil.
---
--- @param val any Whether a boolean or a number.
---
--- @return boolean The boolean value corresponding to the given parameter, according to the table discussed earlier.
---
function affectBool(val)
    local type = type(val)

    if type == "boolean" then
        -- Nothing to do, the value is already a boolean
        return val
    elseif type == "number" then
        assert(val >= 0, "{ \"err\":\"Illegal argument!\" }")

        return (val > 0)
    else
        return nil
    end
end