---
--- Generated by EmmyLua(https://github.com/EmmyLua)
---
--- A script that contains all global functions that may be useful to services.
---
--- @author RedNeath
--- @since 1.0.0
---
--- @licence MIT (https://github.com/Kamigami-no-Tanjou/KoishiTetsu-x-RyouwasaChimura/blob/main/LICENSE)
---

---
--- Turns the given value to a valid SQL string.
---
--- @param val any The value to turn into a string.
---
--- @return string The valid SQL string to send to the database.
---
function varchar(val)
    if val == nil then
        return nil
    else
        return "'" .. val .. "'"
    end
end