---
--- Generated by EmmyLua(https://github.com/EmmyLua)
---
--- A script that sets the environment for each script that needs mysql connection.
---
--- @author RedNeath
--- @since 1.0.0
---
--- @licence MIT (https://github.com/Kamigami-no-Tanjou/KoishiTetsu-x-RyouwasaChimura/blob/main/LICENSE)
--- @return self
---
local mysql = require 'luasql.mysql'
local params = require 'Chimura.Params'
local Environment = {}

local conf

if params.isTest then
    conf = assert(io.open("dbAuthTest.conf", "r"))
else
    conf = assert(io.open("dbAuth.conf" ,"r"))
end

Environment.env = assert(mysql.mysql())
Environment.con = assert(Environment.env:connect(conf:read("*line"), conf:read("*line"), conf:read("*line")))

---
--- Closes the current connection. Will require to import the script again in order to make new requests.
--- This method is meant to be called when exiting a use case that made a database request !
---
--- @return void
---
function Environment.close()
    Environment.con:close()
    Environment.env:close()
end

return Environment